name: emoji_regex
description: emoji-regex offers a regular expression to match all emoji symbols and sequences (including textual representations of emoji) as per the Unicode Standard.
version: 0.0.5
#publish_to: https://pub.dev
homepage: https://github.com/wittyneko/emoji_regex
repository: https://github.com/wittyneko/emoji_regex

environment:
  sdk: ">=2.12.0 <3.0.0"


dev_dependencies:
  test: ^1.21.0